# tools and scripts
path:
  samtools: /home/milefer7/miniconda3/envs/asc04/bin/samtools
  hisat3n: /home/milefer7/opt/hisat-3n/hisat-3n
  hisat3ntable: /home/milefer7/opt/hisat-3n/hisat-3n-table
  umicollapse: /home/milefer7/miniconda3/envs/asc04/share/umicollapse-1.1.0-0/umicollapse.jar
  bgzip: /home/milefer7/miniconda3/envs/asc04/bin/bgzip
  pigz: /home/milefer7/miniconda3/envs/asc04/bin/pigz
  join_pileup.py: ../bin/join_pileup.py
  group_pileup.py: ../bin/group_pileup.py
  select_sites.py: ../bin/select_sites.py
  filter_sites.py: ../bin/filter_sites.py

# global config
library: INLINE
# library: TAKARAV3
#
# prepare genes index
# premap to rRNA, tRNA and other small RNA
# If study virus, then also premap to virus genome
# customized_genes:
#   - a.fa
#   - b.fa
# library: INLINE
# makedup: false 

# reference genome and index
reference:
  contamination:
    # fa: ~/reference/genome/contamination/contamination.fa
    fa: /home/milefer7/myRes/ASC25-m5C/data/ref/GCA_000819615.1_ViralProj14015_genomic.fna
    hisat3n: /home/milefer7/myRes/ASC25-m5C/data/ref/index/hisat3n/contamination/contamination
  genes:
#    fa: ~/reference/genome/Homo_sapiens.GRCh38.sncRNA.fa
    fa: /home/milefer7/myRes/ASC25-m5C/data/ref/gencode.v47.lncRNA_transcripts.fa
    # fa: /home/milefer7/myRes/ASC25-m5C/data/ref/Homo_sapiens.GRCh38.ncrna.fa
    hisat3n: /home/milefer7/myRes/ASC25-m5C/data/ref/index/hisat3n/Homo_sapiens.GRCh38.sncRNA/Homo_sapiens.GRCh38.sncRNA
  genome:
#    fa: ~/reference/genome/Homo_sapiens.GRCh38.genome.fa
    fa: /home/milefer7/myRes/ASC25-m5C/data/ref/GRCh38.p14.genome.fa
    hisat3n: /home/milefer7/myRes/ASC25-m5C/data/ref/index/hisat3n/Homo_sapiens.GRCh38.genome/Homo_sapiens.GRCh38.genome

# Sample name should be indentical and listed in the 2nd level of the yaml file
# Each sample will be analysis seperately, but
# samples sharing the same group id will be regared as biological replicates and combined in the comparing step
samples:
  CONTROL-rep1:
    data:
      - R1: ../data/SRR23538290_1.fastq.gz
    group: CONTROL
  # DRUG-rep1:
  #   data:
  #     - R1: ../data/SRR23538291_1.fastq.gz 
  #   group: DRUG
  # DRUG-rep2:
  #   data:
  #     - R1: ../data/SRR23538292_1.fastq.gz
  #   group: DRUG
