data_dir: ../data
ref_dir: ../ref
src_dir: ../src

ref_GRCh38:
  contamination:
    fa: ~/reference/genome/contamination/contamination.fa
    hisat3n: ~/reference/index/hisat3n/contamination/contamination
  genes:
    fa: ~/reference/genome/Homo_sapiens.GRCh38.sncRNA.fa
    hisat3n: ~/reference/index/hisat3n/Homo_sapiens.GRCh38.sncRNA/Homo_sapiens.GRCh38.sncRNA
  genome:
    fa: ~/reference/genome/Homo_sapiens.GRCh38.genome.fa
    hisat3n: ~/reference/index/hisat3n/Homo_sapiens.GRCh38.genome/Homo_sapiens.GRCh38.genome

samples:
  DMSO-rep1:
    data:
      - R1: ../data/test1_R1.fq.gz
        R2: ../data/test1_R2.fq.gz
    group: DMSO
