# tools and scripts
path:
  samtools: /home/milefer7/miniconda3/envs/asc04/bin/samtools
  hisat3n: /home/milefer7/opt/hisat-3n/hisat-3n
  hisat3ntable: /home/milefer7/opt/hisat-3n/hisat-3n-table
  umicollapse: /home/milefer7/miniconda3/envs/asc04/share/umicollapse-1.1.0-0/umicollapse.jar
  bgzip: /home/milefer7/miniconda3/envs/asc04/bin/bgzip
  join_pileup.py: ../bin/join_pileup.py
  group_pileup.py: ../bin/group_pileup.py
  select_sites.py: ../bin/select_sites.py
  filter_sites.py: ../bin/filter_sites.py

# global config
library: INLINE

# prepare genes index
# premap to rRNA, tRNA and other small RNA
# If study virus, then also premap to virus genome
customized_genes:
  - ../data/ref/fastq/NSUN2.fa
  - ../data/ref/fastq/DNMT2.fa
makedup: false 

# reference genome and index
reference:
  contamination:
    fa: ../data/ref/fastq/rRNA.fa
    hisat3n: ../data/ref/index/rRNA
  genes:
    fa: ../data/ref/fastq/tRNA.fa
    hisat3n: ../data/ref/index/tRNA
  genome:
    fa: ../data/ref/fastq/GRCh38.p14.genome.fa
    hisat3n: ../data/ref/index/Homo_sapiens.GRCh38.genome

# Sample name should be indentical and listed in the 2nd level of the yaml file
# Each sample will be analysis seperately, but
# samples sharing the same group id will be regared as biological replicates and combined in the comparing step
samples:
  SRR23538290:
    data:
      - R1: ../data/samples/SRR23538290_1.fastq.gz
    group: DRUG
  SRR23538291:
    data:
      - R1: ../data/samples/SRR23538291_1.fastq.gz 
    group: DRUG
  SRR23538292:
    data:
      - R1: ../data/samples/SRR23538292_1.fastq.gz
    group: DRUG
